config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:create, :new]
  end
  resources :doses, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :ingredient_id, uniqueness: { scope: :cocktail }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail
    else
      render new_cocktail_path
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to @cocktail
    else
      render 'cocktails/show'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(cocktail) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.button :submit, class: "btn btn-primary btn-lg" %>
<% end %>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_path "background.jpg" %>);">
  <div class="banner-content">
    <%= image_tag "cocktail.svg", id: "logo" %>
    <h1>Tropical  Cocktails</h1>
  </div>
</div>

<div class="drinks-list">
  <h2 class="text-center">Would you like to have a drink?</h2>
  <h3 class="text-center">Our selection of cocktails</h3>
  <%= link_to 'Create a new cocktail', new_cocktail_path, class: "btn btn-primary btn-lg"  %>
  <div class="container">
    <div class="row">
      <% @cocktails.each do |cocktail| %>
      <%= render 'components/card', input: cocktail %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <h1>Create a new cocktail</h1>
  <div class="row">
    <div class="col-md-6">
      <%= render 'form', cocktail: @cocktail %>
    </div>
  </div>
  <%= link_to 'Go back', cocktails_path  %>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <h1><%= @cocktail.name %></h1>
  <div class="row">
    <div class="col-md-6">
      <%= cl_image_tag @cocktail.photo, class: "cocktail-pic"%>
    </div>
    <div class="col-md-6">
      <ul>
      <% @cocktail.doses.each do |dose| %>
        <li>
          <i class="fas fa-glass-martini"></i> <%= dose.ingredient.name %> ( <%= dose.description %> )
          <%= link_to " ", dose_path(dose), method: :delete, class: "fas fa-times" %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <h2>Add an ingredient</h2>
      <%= render 'doses/form', cocktail: @cocktail, dose: @dose %>
    </div>
  </div>

<!--   <div class="form-medium">
  </div> -->
  <p><%= link_to 'Go back', cocktails_path %></p>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for([cocktail, dose]) do |f| %>
  <%= f.input :description, label: "Amount" %>
  <%= f.association :ingredient %>
  <%= f.button :submit, class: "btn btn-primary btn-lg" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>